controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:
    update_rate: 50

    left_wheel_names:
      - front_left_wheel_joint
      - rear_left_wheel_joint

    right_wheel_names:
      - front_right_wheel_joint
      - rear_right_wheel_joint

    wheels_per_side: 2
    wheel_separation: 0.7
    wheel_radius: 0.2

    publish_rate: 50.0
    cmd_vel_timeout: 0.5

    use_stamped_vel: false
    enable_odom_tf: true

    base_frame_id: base_footprint
    odom_frame_id: odom

    open_loop: false

    # Limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 10.0
        min_velocity: -10.0
        has_acceleration_limits: true
        max_acceleration: 5.0
        min_acceleration: -5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 5.0
        min_velocity: -5.0
        has_acceleration_limits: true
        max_acceleration: 2.5
        min_acceleration: -2.5
