controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:

    left_wheel_names:
      - front_left_wheel_joint
      - rear_left_wheel_joint

    right_wheel_names:
      - front_right_wheel_joint
      - rear_right_wheel_joint

    wheel_separation: 1.35
    wheel_radius: 0.292

    publish_rate: 50.0
    cmd_vel_timeout: 0.5

    use_stamped_vel: false
    enable_odom_tf: true

    base_frame_id: base_link
    odom_frame_id: odom

    open_loop: false
