# MAVROS Config for Universal Kit
mavros:
  ros__parameters:
    startup_px4_usb_quirk: true
    plugin_allowlist:
      - sys_status
      - sys_time
      - imu
      - local_position
      - global_position
      - setpoint_velocity
      - cmd_vel
      - param
      - rc_io
      - command

    # IMU Config
    imu:
      frame_id: "base_link"
      linear_acceleration_stdev: 0.0003
      angular_velocity_stdev: 0.02
      orientation_stdev: 1.0
      magnetic_stdev: 0.0

    # Local Position
    local_position:
      frame_id: "odom"
      tf:
        send: true
        frame_id: "odom"
        child_frame_id: "base_link"
        send_fcu: false

    # Setpoint Velocity
    setpoint_velocity:
      mav_frame: BODY_NED
