slam_toolbox:
  ros__parameters:

    # Solver Parameters
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Toolbox Parameters
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping # or localization
    min_laser_range: 0.2 # Avoid 0.0 warning and potential crash

    # Logger Parameters
    # (Default values are usually sufficient)

    # Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349      
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # Scan Matcher Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  

    # Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Loop Closure Parameters
    loop_search_maximum_distance: 10.0
    loop_search_maximum_iterations: 30
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Scan Matcher Scan Parameters
    max_range: 30.0
    min_range: 0.1
    max_proximity_node_distance: 5.0
    proximity_step_size: 1.0
    edge_fitness_threshold: 0.1
    
    # Map Parameters
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.02
    map_update_interval: 5.0
    do_loop_closing: true
    publish_visualize_graph: true
    stack_size_to_use: 40000000 
    enable_interactive_mode: true
